# Generated by Django 4.2.13 on 2026-05-08 12:26

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECORD_CREATED', 'Record Created'), ('RECORD_UPDATED', 'Record Updated'), ('SYNC_QUEUED', 'Sync Queued'), ('SYNC_CONFIRMED', 'Sync Confirmed'), ('SYNC_FAILED', 'Sync Failed'), ('PII_STRIPPED', 'PII Stripped from Request')], db_index=True, max_length=32)),
                ('medicine_batch', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(db_index=True, max_length=255)),
                ('batch_number', models.CharField(max_length=64, unique=True)),
                ('atc_code', models.CharField(blank=True, help_text='WHO Anatomical Therapeutic Chemical classification code', max_length=10)),
                ('quantity', models.PositiveIntegerField(validators=[app.models.validate_positive])),
                ('unit_of_measure', models.CharField(default='units', max_length=32)),
                ('facility_code', models.CharField(db_index=True, help_text='Anonymous facility identifier – not linked to staff names', max_length=32)),
                ('district_code', models.CharField(blank=True, max_length=16)),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField(auto_now_add=True)),
                ('document_hash', models.CharField(help_text='SHA-256 hex digest of the procurement PDF – stored on Solana', max_length=64, unique=True, validators=[app.models.validate_sha256])),
                ('on_chain_signature', models.CharField(blank=True, help_text='Solana transaction signature once the hash is confirmed on-chain', max_length=128)),
                ('is_synced', models.BooleanField(db_index=True, default=False)),
                ('stock_status', models.CharField(choices=[('ADEQUATE', 'Adequate'), ('LOW', 'Low'), ('CRITICAL', 'Critical'), ('OUT_OF_STOCK', 'Out of Stock')], default='ADEQUATE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['drug_name', 'facility_code'], name='app_medicin_drug_na_d7415f_idx'), models.Index(fields=['is_synced'], name='app_medicin_is_sync_3e8ee5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockchainSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_entry', to='app.medicinerecord')),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
    ]
